# Generated by Django 5.1.5 on 2025-01-19 07:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('catalogs', '0001_initial'),
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.TextField()),
                ('image', models.ImageField(default='default_image.jpg', upload_to='product_images/')),
                ('slug', models.SlugField(unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalogs.catalog')),
                ('color', models.ManyToManyField(related_name='products', to='colors.color')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
